name: demo-github-actions  
#Opcional - Como o nome do workflow irá aparecer na aba actions do repositório de GitHub.

on: push #Especifica o evento que aciona automaticamente o arquivo do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v2
      with:
          node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: ACR Login
      run: az acr login --name demogithub.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
    
    - name: Docker build
      run: docker build . -t demogithub.azurecr.io/node-web-app

    - name: Docker push
      run: docker push demogithub.azurecr.io/node-web-app
