name: demo-github-actions  
#Opcional - Como o nome do workflow irá aparecer na aba actions do repositório de GitHub.

on: push #Especifica o evento que aciona automaticamente o arquivo do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v2
      with:
          node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: ACR Login and push
      uses: elgohr/acr-login-action@0.1
      with:
        # The ACR service principal to use for login
        service_principal: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}} 
        # The password of the service principal
        service_principal_password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
        # The ACR tenant to use for login
        tenant: bc4e42e7-a36b-477e-a559-a37af92110c5
        # The ACR registry to use
        registry: DemoGithub
        # The ACR repository to use
        repository: sample-node
