name: demo-github-actions  
#Opcional - Como o nome do workflow irá aparecer na aba actions do repositório de GitHub.

on: push #Especifica o evento que aciona automaticamente o arquivo do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up node
      uses: actions/setup-node@v2
      with:
          node-version: '14'
    
    - name: Install dependencies
      run: npm install

    - name: ACR Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.SERVICE_PRINCIPAL }}
        password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
        login-server: demogithub.azurecr.io
    
    - name: Docker build
      run: docker build . -t demogithub.azurecr.io/node-web-app

    - name: Docker push
      run: docker push demogithub.azurecr.io/node-web-app
        
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: 
        # Tags override for Docker image
        tags: # optional
        # Target Docker registry
        registry: 
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: # optional, default is Dockerfile
        # Directory to run `docker build` from, if not project root
        directory: # optional
        # Docker build arguments passed via --build-arg
        buildArgs: # optional
        # Docker build labels passed via --label
        labels: # optional
        # Docker build target passed via --target
        target: # optional
        # Docker registry username
        username: # optional
        # Docker registry password
        password: # optional
        # GitHub organization to push image to (if not current)
        gitHubOrg: # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: # optional, default is false
        # Suffixes a build timestamp to the branch-based Docker tag
        addTimestamp: # optional, default is false
